# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5589a008c8071792b62b5d2d7ecaf9cc5590d9db812c1d6168fb2779e2aaba7c3584f58fa689be3dde8f36d8f5aaaa0fc566de7dbba37497b60c9a48fe631412

test:
  secret_key_base: 92b0f46e2e8c8c323d3afb807c092f50447caca0125b44d007192b7094b5792e07c5741c91320218b5de7281c07e40dc3179a666f07740220b9de255bfe22e55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
